"""
Simplified SAS parser using regex patterns
This parser handles common SAS DATA step and PROC step patterns
"""
import re
from typing import List, Optional, Tuple, Dict
from ..ast.field_ast import (
    FieldNode, FieldOperationType, DataStepNode, 
    ProcStepNode, SASProgram
)
from .preprocessor import preprocess

# Common SAS keywords and functions that should not be treated as field references
SAS_KEYWORDS = {
    'sum', 'mean', 'max', 'min', 'count', 'put', 'input', 
    'substr', 'trim', 'left', 'right', 'upcase', 'lowcase',
    'if', 'then', 'else', 'do', 'end', 'where', 'and', 'or',
    'data', 'set', 'merge', 'by', 'run', 'proc', 'quit'
}

# Top-level statements that are intentionally not part of field lineage and so
# must not raise "unrecognized statement" warnings.
_BENIGN_TOP_LEVEL = {
    'libname', 'filename', 'options', 'option', 'goptions', 'title', 'footnote',
    'ods', 'dm', 'x', 'endsas', 'run', 'quit', 'data', 'proc',
    'cards', 'datalines', 'cards4', 'datalines4',
}

# DATA-step statements that change the shape of the output and so can hide
# lineage. Declarative statements (LENGTH, FORMAT, LABEL, INPUT, RETAIN, ...)
# are intentionally *not* listed: they do not affect field lineage and warning
# about them is just noise. The set is aggregated per DATA step.
_UNSUPPORTED_IN_DATA = {
    'drop', 'keep', 'rename', 'if', 'where', 'select', 'when', 'otherwise',
}

# Procs that only read/report and never produce a dataset. They are consumed
# without creating a lineage step or emitting warnings.
_READ_ONLY_PROCS = {'PRINT', 'CONTENTS', 'DATASETS', 'CATALOG', 'FORMS'}

# Keep warning payloads bounded on large, messy programs.
_MAX_WARNINGS = 200


class SASParser:
    """
    Parser for SAS code that extracts field lineage information
    """
    
    def __init__(self):
        self.current_line = 0
        self._warned: set = set()
        self._top_unrecognized: List[Tuple[str, str, int]] = []

    def _warn(self, program: SASProgram, message: str, line: Optional[int],
              statement: Optional[str] = None, kind: str = "parse",
              key: Optional[tuple] = None) -> None:
        """Record a deduplicated, capped parse warning on ``program``."""
        if len(program.warnings) >= _MAX_WARNINGS:
            return
        dedup = key or (kind, message)
        if dedup in self._warned:
            return
        self._warned.add(dedup)
        program.add_warning(
            message, line=line,
            statement=(statement or "")[:200] or None, kind=kind,
        )

    @staticmethod
    def _leading(text: str) -> str:
        match = re.match(r"([A-Za-z_]\w*)", text)
        return match.group(1).lower() if match else ""

    @classmethod
    def _is_unrecognized_top(cls, text: str) -> bool:
        """True for a top-level statement that is not a known/benign one."""
        if text.startswith("%") or text.startswith("*"):
            return False
        token = cls._leading(text)
        return bool(token) and token not in _BENIGN_TOP_LEVEL

    def parse(self, sas_code: str, expand_macros: bool = False, include_base: Optional[str] = None) -> SASProgram:
        """
        Parse SAS code end-to-end and return a SASProgram with field lineage.

        The source is tokenised into statements (semicolon-delimited, with
        comments and inline ``datalines``/``cards`` data removed) so that
        compact one-line steps such as ``data x; set y; run;`` and multi-
        statement lines are handled correctly across the whole file.

        When ``expand_macros`` is True, SAS ``%macro`` definitions are expanded
        first so steps generated by macros become plain code. Expansion is
        non-destructive (it never drops a step the source already contains).
        It is off by default because precise macro expansion of arbitrary real
        SAS needs a full macro engine; enable it for files that use the
        deterministic ``%do``/``%let``/``%if``/``%sysfunc`` subset.

        ``%include`` is only resolved when ``include_base`` is a directory.
        Included files are read from that directory (or below) only.
        """
        program = SASProgram()
        self._warned = set()
        self._top_unrecognized = []
        if expand_macros:
            sas_code = preprocess(sas_code, include_base=include_base)
        stmts = self._tokenize(sas_code)

        total = len(stmts)
        i = 0
        while i < len(stmts):
            text, line = stmts[i]
            self.current_line = line
            upper = text.upper()
            if not text:
                i += 1
                continue
            if re.match(r'^DATA\b', upper):
                data_step, i = self._parse_data_step(stmts, i, program)
                if data_step:
                    program.add_data_step(data_step)
                continue
            if re.match(r'^PROC\b', upper):
                proc_step, i = self._parse_proc_step(stmts, i, program)
                if proc_step:
                    program.add_proc_step(proc_step)
                continue
            if self._is_unrecognized_top(text):
                self._top_unrecognized.append((self._leading(upper) or upper[:12].lower(), text, line))
            i += 1

        self._flush_unrecognized(program)
        ignored = len(self._top_unrecognized)
        program.stats = {
            "statements": total,
            "ignored": ignored,
            "coverage": round(100.0 * (total - ignored) / total, 1) if total else 100.0,
        }
        return program

    def _flush_unrecognized(self, program: SASProgram) -> None:
        """Summarise top-level statements that belong to no DATA/PROC step."""
        if not self._top_unrecognized:
            return
        assignments = [t for _t, t, _l in self._top_unrecognized
                       if re.match(r"[A-Za-z_]\w*\s*=", t)]
        if assignments:
            self._warn(
                program,
                f"{len(assignments)} statement(s) could not be attributed to a DATA/PROC step "
                f"(e.g. '{assignments[0][:60]}'); they were ignored",
                None, None, kind="out-of-step", key=("out-of-step",),
            )
        others: Dict[str, Tuple[str, int]] = {}
        for token, text, line in self._top_unrecognized:
            if re.match(r"[A-Za-z_]\w*\s*=", text):
                continue
            others.setdefault(token, (text, line))
        for token, (text, line) in list(others.items())[:10]:
            self._warn(
                program,
                f"Unrecognized top-level statement (ignored): '{text[:80]}'",
                line, text, kind="unknown-statement", key=("top", token),
            )

    def _tokenize(self, sas_code: str) -> List[Tuple[str, int]]:
        """
        Split SAS source into logical statements ``(text, line)``.

        Comments are stripped, statements are delimited by ``;`` and inline
        ``datalines``/``cards`` (and ``*4`` variants) blocks are consumed as
        opaque data so their rows are never mistaken for code.
        """
        text = SASCodeCleaner.remove_comments(sas_code)
        stmts: List[Tuple[str, int]] = []
        cur = ""
        cur_line = 0
        cards = False

        for ln_idx, raw in enumerate(text.split("\n"), start=1):
            line = raw
            while line:
                if cards:
                    j = line.find(";")
                    if j == -1:
                        line = ""           # consume whole card-data line
                    else:
                        line = line[j + 1:]
                        cards = False
                    continue
                j = line.find(";")
                if j == -1:
                    if not cur_line:
                        cur_line = ln_idx
                    cur = (cur + " " + line).strip() if cur else line.strip()
                    break
                piece = line[:j].strip()
                if not cur_line:
                    cur_line = ln_idx
                cur = (cur + " " + piece).strip() if cur else piece
                stmt_text = cur.strip()
                stmt_line = cur_line
                cur, cur_line = "", 0
                if stmt_text:
                    stmts.append((stmt_text, stmt_line))
                    # A bare datalines/cards statement opens an inline data block.
                    if re.match(r"^(DATALINES4?|CARDS4?)\s*$", stmt_text.upper()):
                        cards = True
                line = line[j + 1:]
        if cur.strip():
            stmts.append((cur.strip(), cur_line or 1))
        return stmts
    
    def _parse_data_step(self, stmts, start_line: int,
                         program: Optional[SASProgram] = None) -> Tuple[Optional[DataStepNode], int]:
        """
        Parse a DATA step from a list of statements, returning the step and the
        index just after its terminator (``RUN;``/``QUIT;``).
        """
        text, line = stmts[start_line]
        # Permissive: capture ``lib.table``, ``&macro.name`` or ``%name`` too.
        target_match = re.search(r'DATA\s+([^\s;]+)', text, re.IGNORECASE)
        full_target = target_match.group(1) if target_match else ""
        # Keep the full ``lib.table`` name so the table is not mistaken for its
        # library (``lib.C111_tabla`` must not become just ``lib``).
        output_table = full_target
        if not output_table and program is not None:
            self._warn(program, f"Could not read the DATA target: '{text[:80]}'",
                       line, text, kind="data-target")
        data_step = DataStepNode(output_table=output_table or "(unknown)")

        i = start_line + 1
        terminated = False
        unsupported: set = set()
        while i < len(stmts):
            stmt, ln = stmts[i]
            upper = stmt.upper()
            # Terminators end the step (RUN; or QUIT;).
            if upper.startswith('RUN') or upper.startswith('QUIT'):
                i += 1
                terminated = True
                break
            # A datalines/cards block is opaque data — nothing to extract.
            if re.match(r'^(DATALINES4?|CARDS4?)\b', upper):
                i += 1
                terminated = True
                break
            # A new step before a terminator means the current one is truncated.
            if re.match(r'^DATA\s', upper) or re.match(r'^PROC\s', upper):
                if program is not None:
                    self._warn(
                        program,
                        f"DATA step '{data_step.output_table}' has no RUN; before the next "
                        f"step at line {ln}",
                        line, text, kind="unterminated",
                        key=("unterminated", "data", data_step.output_table),
                    )
                break

            if upper.startswith('SET '):
                set_match = re.search(r'SET\s+([\w.\s]+)', stmt, re.IGNORECASE)
                if set_match:
                    data_step.input_tables.extend(
                        t for t in set_match.group(1).split() if t.strip())
            elif upper.startswith('MERGE '):
                merge_match = re.search(r'MERGE\s+([\w.\s]+)', stmt, re.IGNORECASE)
                if merge_match:
                    data_step.input_tables.extend(
                        t for t in merge_match.group(1).split() if t.strip())
            elif upper.startswith('BY '):
                by_match = re.search(r'BY\s+([\w\s]+)', stmt, re.IGNORECASE)
                if by_match:
                    data_step.merge_keys.extend(k for k in by_match.group(1).split() if k.strip())
            else:
                lead = self._leading(upper)
                if lead in _UNSUPPORTED_IN_DATA:
                    unsupported.add(lead)
                assignment_match = re.search(r'(\w+)\s*=\s*(.+)', stmt)
                if assignment_match:
                    field_name = assignment_match.group(1)
                    expression = assignment_match.group(2).strip()
                    field_node = FieldNode(
                        name=field_name,
                        table=output_table,
                        operation=FieldOperationType.ASSIGNMENT,
                        expression=expression,
                        source_line=ln,
                    )
                    deps = self._extract_field_references(expression, data_step.input_tables)
                    for dep_name, dep_table in deps:
                        field_node.add_dependency(FieldNode(name=dep_name, table=dep_table))
                    data_step.add_field(field_node)
            i += 1

        if unsupported and program is not None:
            self._warn(
                program,
                f"DATA step '{data_step.output_table}' uses statement(s) not modelled for "
                f"lineage ({', '.join(sorted(unsupported))}); lineage may be incomplete",
                line, text, kind="unsupported",
                key=("data-unsupported", data_step.output_table),
            )
        if not terminated and program is not None:
            self._warn(
                program,
                f"DATA step '{data_step.output_table}' may be unterminated (no RUN;/QUIT; "
                f"before end of file)",
                line, text, kind="unterminated",
                key=("unterminated", "data", data_step.output_table),
            )
        return data_step, i
    
    def _parse_proc_step(self, stmts, start_line: int,
                         program: Optional[SASProgram] = None) -> Tuple[Optional[ProcStepNode], int]:
        """
        Parse a PROC step (simplified), returning the step and the index just
        after its terminator (``RUN;`` or ``QUIT;``).
        """
        text, line = stmts[start_line]

        # Extract PROC name
        match = re.search(r'PROC\s+(\w+)', text, re.IGNORECASE)
        if not match:
            if program is not None:
                self._warn(program, f"Could not read the PROC name: '{text[:80]}'",
                           line, text, kind="proc-name")
            return None, start_line + 1

        proc_name = match.group(1).upper()

        # Read-only procs never produce a dataset: consume the step silently.
        if proc_name in _READ_ONLY_PROCS:
            return None, self._skip_step(stmts, start_line)

        proc_step = ProcStepNode(proc_name=proc_name)

        i = start_line + 1
        terminated = False
        while i < len(stmts):
            stmt, ln = stmts[i]
            upper = stmt.upper()
            if upper.startswith('RUN') or upper.startswith('QUIT'):
                i += 1
                terminated = True
                break
            if re.match(r'^DATA\s', upper) or re.match(r'^PROC\s', upper):
                if program is not None:
                    self._warn(
                        program,
                        f"PROC {proc_name} step has no RUN;/QUIT; before the next "
                        f"step at line {ln}",
                        line, text, kind="unterminated",
                        key=("unterminated", "proc", proc_name),
                    )
                break

            # Extract DATA= option (keep the full lib.table name)
            data_match = re.search(r'DATA\s*=\s*([\w.]+)', stmt, re.IGNORECASE)
            if data_match:
                proc_step.input_table = data_match.group(1)

            # Extract OUT= option (keep the full lib.table name)
            out_match = re.search(r'OUT\s*=\s*([\w.]+)', stmt, re.IGNORECASE)
            if out_match:
                proc_step.output_table = out_match.group(1)

            i += 1

        if not terminated and program is not None:
            self._warn(
                program,
                f"PROC {proc_name} step may be unterminated (no RUN;/QUIT; before "
                f"end of file)",
                line, text, kind="unterminated",
                key=("unterminated", "proc", proc_name),
            )
        return proc_step, i

    def _skip_step(self, stmts, start_line: int) -> int:
        """Index just after a step's RUN;/QUIT;, or at the next step."""
        i = start_line + 1
        while i < len(stmts):
            upper = stmts[i][0].upper()
            if upper.startswith('RUN') or upper.startswith('QUIT'):
                return i + 1
            if re.match(r'^DATA\s', upper) or re.match(r'^PROC\s', upper):
                return i
            i += 1
        return i

    def _extract_field_references(self, expression: str, source_tables: List[str]) -> List[Tuple[str, Optional[str]]]:
        """
        Extract field references from an expression
        Returns list of (field_name, table_name) tuples
        """
        references = []
        
        # Match field names (simple identifiers)
        # Look for table.field or just field
        qualified_refs = re.findall(r'(\w+)\.(\w+)', expression)
        for table, field in qualified_refs:
            references.append((field, table))
        
        # Find unqualified field references
        # Remove function names and operators
        cleaned_expr = re.sub(r'(\w+)\s*\(', '', expression)  # Remove function calls
        tokens = re.findall(r'\b([a-zA-Z_]\w*)\b', cleaned_expr)
        
        # Filter out SAS keywords and functions
        for token in tokens:
            if token.lower() not in SAS_KEYWORDS and not token.isdigit():
                # Try to infer table from source tables
                # Note: This defaults to first table which may be ambiguous
                table = source_tables[0] if source_tables else None
                if (token, table) not in references:
                    references.append((token, table))
        
        return references


class SASCodeCleaner:
    """
    Utility to clean and preprocess SAS code
    """
    
    @staticmethod
    def remove_comments(code: str) -> str:
        """Remove comments from SAS code"""
        # Remove /* */ style comments
        code = re.sub(r'/\*.*?\*/', '', code, flags=re.DOTALL)
        # Remove * style comments (line comments)
        code = re.sub(r'^\s*\*[^;]*;', '', code, flags=re.MULTILINE)
        return code
    
    @staticmethod
    def normalize_whitespace(code: str) -> str:
        """Normalize whitespace in SAS code"""
        # Replace multiple spaces with single space
        code = re.sub(r'[ \t]+', ' ', code)
        return code
