"""SAS step parser with token-aware table references and explicit diagnostics.

Field expressions still use the legacy heuristic extractor. Table analysis
records its unsupported constructs rather than claiming full SAS semantics.
"""
import re
from typing import List, Optional, Tuple
from ..ast.field_ast import (
    FieldNode, FieldOperationType, DataStepNode, 
    ProcStepNode, SASProgram
)
from .preprocessor import preprocess
from ..ast.table_ast import Diagnostic, TableReference
from .scanner import dataset_list, dataset_options, read_name, scan_statements, strip_comments, tokenize

# Common SAS keywords and functions that should not be treated as field references
SAS_KEYWORDS = {
    'sum', 'mean', 'max', 'min', 'count', 'put', 'input', 
    'substr', 'trim', 'left', 'right', 'upcase', 'lowcase',
    'if', 'then', 'else', 'do', 'end', 'where', 'and', 'or',
    'data', 'set', 'merge', 'by', 'run', 'proc', 'quit'
}


class SASParser:
    """
    Parser for SAS code that extracts field lineage information
    """
    
    def __init__(self):
        self.current_line = 0
        
    def parse(self, sas_code: str, expand_macros: bool = False, include_base: Optional[str] = None) -> SASProgram:
        """
        Parse SAS code end-to-end and return a SASProgram with field lineage.

        The source is tokenised into statements (semicolon-delimited, with
        comments and inline ``datalines``/``cards`` data removed) so that
        compact one-line steps such as ``data x; set y; run;`` and multi-
        statement lines are handled correctly across the whole file.

        When ``expand_macros`` is True, SAS ``%macro`` definitions are expanded
        first so steps generated by macros become plain code. Expansion is
        non-destructive (it never drops a step the source already contains).
        It is off by default because precise macro expansion of arbitrary real
        SAS needs a full macro engine; enable it for files that use the
        deterministic ``%do``/``%let``/``%if``/``%sysfunc`` subset.

        ``%include`` is only resolved when ``include_base`` is a directory.
        Included files are read from that directory (or below) only.
        """
        program = SASProgram()
        self.program = program
        if expand_macros:
            sas_code = preprocess(sas_code, include_base=include_base)
            program.coordinate_space = 'expanded'
            program.diagnostics.append(Diagnostic(
                'heuristic_macro_expansion',
                'Legacy macro expansion is approximate; names are candidates, not verified runtime names. '
                'Line numbers refer to expanded text, not original macro definitions.'))
        scanned, issues = scan_statements(sas_code)
        program.diagnostics.extend(Diagnostic(x.code, x.message, x.line) for x in issues)
        stmts = [(stmt.text, stmt.line) for stmt in scanned]

        i = 0
        macro_depth = 0
        while i < len(stmts):
            text, line = stmts[i]
            self.current_line = line
            tokens = tokenize(text)
            upper = tokens[0].upper if tokens else ''
            if not text:
                i += 1
                continue
            if re.match(r'%macro\b', text, re.I):
                macro_depth += 1
                self._diagnostic('unexpanded_macro', 'Macro definition requires expansion; its body is not an executed step.', line)
            elif re.match(r'%mend\b', text, re.I):
                macro_depth = max(0, macro_depth - 1)
            elif macro_depth:
                pass
            elif upper == 'DATA':
                data_step, i = self._parse_data_step(stmts, i)
                if data_step:
                    program.add_data_step(data_step)
                continue
            elif upper == 'PROC':
                proc_step, i = self._parse_proc_step(stmts, i)
                if proc_step:
                    program.add_proc_step(proc_step)
                continue
            elif text.startswith('%'):
                self._diagnostic('unexpanded_macro', 'Macro statement or invocation is not resolved.', line)
            elif upper in {'LIBNAME', 'FILENAME', 'OPTIONS'}:
                self._diagnostic('session_configuration', 'Session configuration is recorded only as a limitation; physical library/file identities are not resolved.', line)
            elif upper == 'ODS':
                self._diagnostic('unsupported_io', 'ODS output datasets and destinations are not modeled.', line)
            elif upper not in {'', 'RUN', 'QUIT', 'TITLE', 'FOOTNOTE'}:
                self._diagnostic('unsupported_statement', 'Open-code statement is not modeled: ' + tokens[0].text, line)
            i += 1

        return program

    def _tokenize(self, sas_code: str) -> List[Tuple[str, int]]:
        """
        Split SAS source into logical statements ``(text, line)``.

        Comments are stripped, statements are delimited by ``;`` and inline
        ``datalines``/``cards`` (and ``*4`` variants) blocks are consumed as
        opaque data so their rows are never mistaken for code.
        """
        statements, _ = scan_statements(sas_code)
        return [(stmt.text, stmt.line) for stmt in statements]

    def _diagnostic(self, code: str, message: str, line: int):
        self.program.diagnostics.append(Diagnostic(code, message, line))

    def _reference(self, step, name: str, access: str, line: int):
        if name.lower() == '_null_':
            return
        tokens = tokenize(name)
        symbolic = any(token.kind == 'macro' for token in tokens)
        # Double-quoted name literals can also contain active macro triggers.
        symbolic = symbolic or any(
            token.kind == 'name_literal' and token.text.startswith('"')
            and re.search(r'[&%][A-Za-z_]', token.text) for token in tokens)
        reason = 'Unresolved macro expression in dataset name.' if symbolic else None
        resolution = 'symbolic' if symbolic else 'literal'
        if not symbolic and (name.lower() in {'_last_', '_data_', '_all_'}
                             or sum(token.text == '.' for token in tokens) > 1):
            resolution = 'unknown'
            reason = 'Session-dependent or unsupported dataset name.'
            self._diagnostic('unsupported_table_name', reason + ' ' + name, line)
        step.table_references.append(TableReference(
            name, access, line, resolution, reason))
        if symbolic:
            self._diagnostic('unresolved_table_name', reason + ' ' + name, line)

    def _runtime_effects(self, statement: str, line: int):
        words = [token.upper for token in tokenize(statement)]
        if any(word in {'SYMPUT', 'SYMPUTX', 'SYMGET', 'EXECUTE', 'DOSUBL', 'RESOLVE'} for word in words):
            self._diagnostic('runtime_macro_effect',
                             'Runtime macro state or generated code requires execution evidence; it is not evaluated.', line)
        if any(token.kind == 'macro' and token.text.startswith('%') for token in tokenize(statement)):
            self._diagnostic('unexpanded_macro', 'Macro code within the step is not resolved.', line)
    
    def _parse_data_step(self, stmts, start_line: int) -> Tuple[Optional[DataStepNode], int]:
        """
        Parse a DATA step from a list of statements, returning the step and the
        index just after its terminator (``RUN;``/``QUIT;``).
        """
        text, line = stmts[start_line]
        tokens = tokenize(text)
        names, incomplete = dataset_list(text[tokens[0].end:])
        if incomplete:
            self._diagnostic('unsupported_dataset_list', 'DATA output list could not be fully resolved.', line)
        if not names:
            self._diagnostic('missing_output_name', 'DATA statement has no supported output dataset name.', line)
            return None, start_line + 1

        output_table = names[0]
        data_step = DataStepNode(output_table=output_table,
                                 output_tables=[name for name in names if name.lower() != '_null_'],
                                 source_line=line)
        for name in names:
            self._reference(data_step, name, 'write', line)
        if any(option == 'VIEW' for option, _ in dataset_options(text, ('VIEW',))):
            self._diagnostic('deferred_view', 'DATA-step view execution and deferred dependencies are not modeled.', line)

        i = start_line + 1
        while i < len(stmts):
            stmt, ln = stmts[i]
            tokens = tokenize(stmt)
            upper = tokens[0].upper if tokens else ''
            if upper in {'DATA', 'PROC'}:
                break  # A new step also terminates the preceding step.
            # Terminators end the step (RUN; or QUIT;).
            if upper in {'RUN', 'QUIT'}:
                i += 1
                break
            # A datalines/cards block is opaque data — nothing to extract.
            if upper in {'DATALINES', 'DATALINES4', 'CARDS', 'CARDS4'}:
                i += 1
                continue

            self._runtime_effects(stmt, ln)
            if upper not in {'SET', 'MERGE', 'UPDATE', 'MODIFY'} and any(
                    token.upper in {'SET', 'MERGE', 'UPDATE', 'MODIFY'} for token in tokens):
                self._diagnostic('conditional_dataset_io', 'Embedded or conditional dataset I/O is not fully resolved.', ln)
            if upper in {'SET', 'MERGE', 'UPDATE', 'MODIFY'}:
                inputs, incomplete = dataset_list(stmt[tokens[0].end:])
                data_step.input_tables.extend(inputs)
                for name in inputs:
                    self._reference(data_step, name, 'read', ln)
                if incomplete:
                    self._diagnostic('unsupported_dataset_list', 'Dataset prefix/range list or dynamic expression needs catalog-aware resolution.', ln)
                if upper in {'UPDATE', 'MODIFY'}:
                    self._diagnostic('unsupported_mutation', upper + ' mutation semantics are not modeled.', ln)
            elif upper == 'BY':
                by_match = re.search(r'BY\s+([\w\s]+)', stmt, re.IGNORECASE)
                if by_match:
                    data_step.merge_keys.extend(k for k in by_match.group(1).split() if k.strip())
            else:
                if upper in {'DECLARE', 'DCL', 'INFILE', 'FILE', 'ODS'}:
                    self._diagnostic('unsupported_io', 'Hash-object or external-file I/O is not modeled.', ln)
                assignment_match = re.match(r'(\w+)\s*=\s*(.+)', stmt, re.S)
                if assignment_match:
                    field_name = assignment_match.group(1)
                    expression = assignment_match.group(2).strip()
                    field_node = FieldNode(
                        name=field_name,
                        table=output_table,
                        operation=FieldOperationType.ASSIGNMENT,
                        expression=expression,
                        source_line=ln,
                    )
                    deps = self._extract_field_references(expression, data_step.input_tables)
                    for dep_name, dep_table in deps:
                        field_node.add_dependency(FieldNode(name=dep_name, table=dep_table))
                    data_step.add_field(field_node)
            i += 1

        return data_step, i
    
    def _parse_proc_step(self, stmts, start_line: int) -> Tuple[Optional[ProcStepNode], int]:
        """
        Parse a PROC step (simplified), returning the step and the index just
        after its terminator (``RUN;`` or ``QUIT;``).
        """
        text, line = stmts[start_line]

        # Extract PROC name
        match = re.search(r'PROC\s+(\w+)', text, re.IGNORECASE)
        if not match:
            return None, start_line + 1

        proc_name = match.group(1).upper()
        proc_step = ProcStepNode(proc_name=proc_name, source_line=line)
        if proc_name not in {'SORT', 'PRINT', 'CONTENTS', 'MEANS', 'SUMMARY', 'FREQ', 'APPEND'}:
            self._diagnostic('unsupported_procedure',
                             'Procedure effects are only partially extracted: ' + proc_name, line)

        explicit_sort_output = False
        i = start_line
        while i < len(stmts):
            stmt, ln = stmts[i]
            tokens = tokenize(stmt)
            upper = tokens[0].upper if tokens else ''
            if i > start_line and upper in {'DATA', 'PROC'}:
                break
            if upper == 'QUIT' or (upper == 'RUN' and proc_name not in {'SQL', 'DATASETS'}):
                i += 1
                break

            self._runtime_effects(stmt, ln)
            if upper == 'ODS':
                self._diagnostic('unsupported_io', 'ODS output datasets and destinations are not modeled.', ln)
            for option, name in dataset_options(stmt, ('DATA', 'OUT', 'BASE', 'DUPOUT', 'OUTP', 'OUTEST')):
                if option == 'OUT':
                    explicit_sort_output = True
                if option in {'DATA', 'BASE'}:
                    proc_step.input_table = proc_step.input_table or name
                    self._reference(proc_step, name, 'read', ln)
                if option != 'DATA':
                    proc_step.output_table = proc_step.output_table or name
                    self._reference(proc_step, name, 'write', ln)
            if proc_name == 'SQL':
                self._sql_references(proc_step, tokens, ln)

            i += 1

        if proc_name == 'SORT' and proc_step.input_table and not explicit_sort_output:
            proc_step.output_table = proc_step.input_table
            self._reference(proc_step, proc_step.output_table, 'write', line)
        if not proc_step.input_table and proc_name in {'SORT', 'PRINT', 'CONTENTS', 'MEANS', 'SUMMARY', 'FREQ'}:
            self._diagnostic('implicit_input', 'Procedure default input depends on session state.', line)
        return proc_step, i

    def _sql_references(self, step, tokens, line):
        """Recover basic SQL references; unsupported_procedure marks partiality."""
        for index, token in enumerate(tokens):
            access = None
            after = index + 1
            if token.upper in {'FROM', 'JOIN'}:
                access = 'read'
            elif token.upper == 'TABLE' and index and tokens[index - 1].upper == 'CREATE':
                access = 'write'
            if access:
                name, _ = read_name(tokens, after)
                if name:
                    self._reference(step, name, access, line)
    
    def _extract_field_references(self, expression: str, source_tables: List[str]) -> List[Tuple[str, Optional[str]]]:
        """
        Extract field references from an expression
        Returns list of (field_name, table_name) tuples
        """
        references = []
        
        # Match field names (simple identifiers)
        # Look for table.field or just field
        qualified_refs = re.findall(r'(\w+)\.(\w+)', expression)
        for table, field in qualified_refs:
            references.append((field, table))
        
        # Find unqualified field references
        # Remove function names and operators
        cleaned_expr = re.sub(r'(\w+)\s*\(', '', expression)  # Remove function calls
        tokens = re.findall(r'\b([a-zA-Z_]\w*)\b', cleaned_expr)
        
        # Filter out SAS keywords and functions
        for token in tokens:
            if token.lower() not in SAS_KEYWORDS and not token.isdigit():
                # Try to infer table from source tables
                # Note: This defaults to first table which may be ambiguous
                table = source_tables[0] if source_tables else None
                if (token, table) not in references:
                    references.append((token, table))
        
        return references


class SASCodeCleaner:
    """
    Utility to clean and preprocess SAS code
    """
    
    @staticmethod
    def remove_comments(code: str) -> str:
        """Remove comments from SAS code"""
        return strip_comments(code)
    
    @staticmethod
    def normalize_whitespace(code: str) -> str:
        """Normalize whitespace in SAS code"""
        # Replace multiple spaces with single space
        code = re.sub(r'[ \t]+', ' ', code)
        return code
