"""
Simplified SAS parser using regex patterns
This parser handles common SAS DATA step and PROC step patterns
"""
import re
from typing import List, Optional, Tuple, Dict
from ..ast.field_ast import (
    FieldNode, FieldOperationType, DataStepNode, 
    ProcStepNode, SASProgram
)
from .preprocessor import preprocess

# Common SAS keywords and functions that should not be treated as field references
SAS_KEYWORDS = {
    'sum', 'mean', 'max', 'min', 'count', 'put', 'input', 
    'substr', 'trim', 'left', 'right', 'upcase', 'lowcase',
    'if', 'then', 'else', 'do', 'end', 'where', 'and', 'or',
    'data', 'set', 'merge', 'by', 'run', 'proc', 'quit'
}


class SASParser:
    """
    Parser for SAS code that extracts field lineage information
    """
    
    def __init__(self):
        self.current_line = 0
        
    def parse(self, sas_code: str, expand_macros: bool = False, include_base: Optional[str] = None) -> SASProgram:
        """
        Parse SAS code end-to-end and return a SASProgram with field lineage.

        The source is tokenised into statements (semicolon-delimited, with
        comments and inline ``datalines``/``cards`` data removed) so that
        compact one-line steps such as ``data x; set y; run;`` and multi-
        statement lines are handled correctly across the whole file.

        When ``expand_macros`` is True, SAS ``%macro`` definitions are expanded
        first so steps generated by macros become plain code. Expansion is
        non-destructive (it never drops a step the source already contains).
        It is off by default because precise macro expansion of arbitrary real
        SAS needs a full macro engine; enable it for files that use the
        deterministic ``%do``/``%let``/``%if``/``%sysfunc`` subset.

        ``%include`` is only resolved when ``include_base`` is a directory.
        Included files are read from that directory (or below) only.
        """
        program = SASProgram()
        if expand_macros:
            sas_code = preprocess(sas_code, include_base=include_base)
        stmts = self._tokenize(sas_code)

        i = 0
        while i < len(stmts):
            text, line = stmts[i]
            self.current_line = line
            upper = text.upper()
            if not text:
                i += 1
                continue
            if upper.startswith('DATA '):
                data_step, i = self._parse_data_step(stmts, i)
                if data_step:
                    program.add_data_step(data_step)
                continue
            if upper.startswith('PROC '):
                proc_step, i = self._parse_proc_step(stmts, i)
                if proc_step:
                    program.add_proc_step(proc_step)
                continue
            i += 1

        return program

    def _tokenize(self, sas_code: str) -> List[Tuple[str, int]]:
        """
        Split SAS source into logical statements ``(text, line)``.

        Comments are stripped, statements are delimited by ``;`` and inline
        ``datalines``/``cards`` (and ``*4`` variants) blocks are consumed as
        opaque data so their rows are never mistaken for code.
        """
        text = SASCodeCleaner.remove_comments(sas_code)
        stmts: List[Tuple[str, int]] = []
        cur = ""
        cur_line = 0
        cards = False

        for ln_idx, raw in enumerate(text.split("\n"), start=1):
            line = raw
            while line:
                if cards:
                    j = line.find(";")
                    if j == -1:
                        line = ""           # consume whole card-data line
                    else:
                        line = line[j + 1:]
                        cards = False
                    continue
                j = line.find(";")
                if j == -1:
                    if not cur_line:
                        cur_line = ln_idx
                    cur = (cur + " " + line).strip() if cur else line.strip()
                    break
                piece = line[:j].strip()
                if not cur_line:
                    cur_line = ln_idx
                cur = (cur + " " + piece).strip() if cur else piece
                stmt_text = cur.strip()
                stmt_line = cur_line
                cur, cur_line = "", 0
                if stmt_text:
                    stmts.append((stmt_text, stmt_line))
                    # A bare datalines/cards statement opens an inline data block.
                    if re.match(r"^(DATALINES4?|CARDS4?)\s*$", stmt_text.upper()):
                        cards = True
                line = line[j + 1:]
        if cur.strip():
            stmts.append((cur.strip(), cur_line or 1))
        return stmts
    
    def _parse_data_step(self, stmts, start_line: int) -> Tuple[Optional[DataStepNode], int]:
        """
        Parse a DATA step from a list of statements, returning the step and the
        index just after its terminator (``RUN;``/``QUIT;``).
        """
        text, line = stmts[start_line]
        match = re.search(r'DATA\s+(\w+)', text, re.IGNORECASE)
        if not match:
            return None, start_line + 1

        output_table = match.group(1)
        data_step = DataStepNode(output_table=output_table)

        i = start_line + 1
        while i < len(stmts):
            stmt, ln = stmts[i]
            upper = stmt.upper()
            # Terminators end the step (RUN; or QUIT;).
            if upper.startswith('RUN') or upper.startswith('QUIT'):
                i += 1
                break
            # A datalines/cards block is opaque data — nothing to extract.
            if re.match(r'^(DATALINES4?|CARDS4?)\b', upper):
                i += 1
                break

            if upper.startswith('SET '):
                set_match = re.search(r'SET\s+([\w\s]+)', stmt, re.IGNORECASE)
                if set_match:
                    data_step.input_tables.extend(
                        t for t in set_match.group(1).split() if t.strip())
            elif upper.startswith('MERGE '):
                merge_match = re.search(r'MERGE\s+([\w\s]+)', stmt, re.IGNORECASE)
                if merge_match:
                    data_step.input_tables.extend(
                        t for t in merge_match.group(1).split() if t.strip())
            elif upper.startswith('BY '):
                by_match = re.search(r'BY\s+([\w\s]+)', stmt, re.IGNORECASE)
                if by_match:
                    data_step.merge_keys.extend(k for k in by_match.group(1).split() if k.strip())
            else:
                assignment_match = re.search(r'(\w+)\s*=\s*(.+)', stmt)
                if assignment_match:
                    field_name = assignment_match.group(1)
                    expression = assignment_match.group(2).strip()
                    field_node = FieldNode(
                        name=field_name,
                        table=output_table,
                        operation=FieldOperationType.ASSIGNMENT,
                        expression=expression,
                        source_line=ln,
                    )
                    deps = self._extract_field_references(expression, data_step.input_tables)
                    for dep_name, dep_table in deps:
                        field_node.add_dependency(FieldNode(name=dep_name, table=dep_table))
                    data_step.add_field(field_node)
            i += 1

        return data_step, i
    
    def _parse_proc_step(self, stmts, start_line: int) -> Tuple[Optional[ProcStepNode], int]:
        """
        Parse a PROC step (simplified), returning the step and the index just
        after its terminator (``RUN;`` or ``QUIT;``).
        """
        text, line = stmts[start_line]

        # Extract PROC name
        match = re.search(r'PROC\s+(\w+)', text, re.IGNORECASE)
        if not match:
            return None, start_line + 1

        proc_name = match.group(1).upper()
        proc_step = ProcStepNode(proc_name=proc_name)

        i = start_line + 1
        while i < len(stmts):
            stmt, ln = stmts[i]
            upper = stmt.upper()
            if upper.startswith('RUN') or upper.startswith('QUIT'):
                i += 1
                break

            # Extract DATA= option
            data_match = re.search(r'DATA\s*=\s*(\w+)', stmt, re.IGNORECASE)
            if data_match:
                proc_step.input_table = data_match.group(1)

            # Extract OUT= option
            out_match = re.search(r'OUT\s*=\s*(\w+)', stmt, re.IGNORECASE)
            if out_match:
                proc_step.output_table = out_match.group(1)

            i += 1

        return proc_step, i
    
    def _extract_field_references(self, expression: str, source_tables: List[str]) -> List[Tuple[str, Optional[str]]]:
        """
        Extract field references from an expression
        Returns list of (field_name, table_name) tuples
        """
        references = []
        
        # Match field names (simple identifiers)
        # Look for table.field or just field
        qualified_refs = re.findall(r'(\w+)\.(\w+)', expression)
        for table, field in qualified_refs:
            references.append((field, table))
        
        # Find unqualified field references
        # Remove function names and operators
        cleaned_expr = re.sub(r'(\w+)\s*\(', '', expression)  # Remove function calls
        tokens = re.findall(r'\b([a-zA-Z_]\w*)\b', cleaned_expr)
        
        # Filter out SAS keywords and functions
        for token in tokens:
            if token.lower() not in SAS_KEYWORDS and not token.isdigit():
                # Try to infer table from source tables
                # Note: This defaults to first table which may be ambiguous
                table = source_tables[0] if source_tables else None
                if (token, table) not in references:
                    references.append((token, table))
        
        return references


class SASCodeCleaner:
    """
    Utility to clean and preprocess SAS code
    """
    
    @staticmethod
    def remove_comments(code: str) -> str:
        """Remove comments from SAS code"""
        # Remove /* */ style comments
        code = re.sub(r'/\*.*?\*/', '', code, flags=re.DOTALL)
        # Remove * style comments (line comments)
        code = re.sub(r'^\s*\*[^;]*;', '', code, flags=re.MULTILINE)
        return code
    
    @staticmethod
    def normalize_whitespace(code: str) -> str:
        """Normalize whitespace in SAS code"""
        # Replace multiple spaces with single space
        code = re.sub(r'[ \t]+', ' ', code)
        return code
